name: Publish the released PHAR

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    name: Release PHAR

    steps:
      - name: Extract the tag version
        id: tag
        run: echo ::set-output name=tag::${GITHUB_REF##*v}

      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Install the dependencies
        run: composer install

      - name: Create the PHAR file.
        run: ./pakiti app:build pakiti.phar --build-version=${{ steps.tag.outputs.tag }}

      - name: Upload the PHAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: pakiti.pakiti
          path: builds/pakiti.phar

      - name: Upload the PHAR to release
        run: gh release upload v${{ steps.tag.outputs.tag }} builds/pakiti.phar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
